env:
  contexts:
    - name: Testfire Context
      urls:
        - http://testfire.net/
      includePaths:
        - http://testfire.net/*
      excludePaths: []
      authentication:
        method: form
        parameters:
          loginPageUrl: http://testfire.net/login.jsp
          loginRequestBody: uid={%username%}&passw={%password%}
          loginRequestUrl: http://testfire.net/doLogin
        verification:
        verification:
          method: "poll"
          pollFrequency: 5  # How often to poll (e.g., every 5 requests)
          pollUnits: "requests"
          pollUrl: "http://testfire.net/bank/main.jsp"
          loggedInRegex: "Sign Off"
          loggedOutRegex: "Sign In"
      users:
        - name: test_user
          credentials:
            username: jsmith
            password: demo1234
      sessionManagement:
        method: cookie
        parameters: {}
      technology:
        exclude: []
  parameters:
    failOnError: true
    failOnWarning: false
    progressToStdout: true
  vars: {}
jobs:
  - name: passiveScan-config
    type: passiveScan-config
    parameters:
      enableTags: false
      scanOnlyInScope: true
    rules: []
  - name: spider
    type: spider
    parameters:
      context: Testfire Context
      user: test_user
      maxChildren: 0
      maxDepth: 0
      maxDuration: 0
      url: ""
  - name: "spiderAjax"
    type: "spiderAjax"
    parameters:
      context: "Testfire Context"
      user: "test_user"
      maxDuration: 60
      maxCrawlDepth: 10
      numberOfBrowsers: 8
      runOnlyIfModern: false
      url: ""
  - name: passiveScan-wait
    type: passiveScan-wait
    parameters: {}
  - name: activeScan
    type: activeScan
    parameters:
      context: Testfire Context
      user: test_user
      maxRuleDurationInMins: 0
      maxScanDurationInMins: 60
      policy: ""
      policyDefinition:
        defaultStrength: medium
        defaultThreshold: medium
        rules:
          - id: 40018 # Rule ID for SQLi in ZAP 
          strength: insane # Turn it up to 11
  - name: report
    type: report
    parameters:
      reportDescription: ""
      reportDir: /dast_home/test_output/
      reportFile: ZAP-Report
      reportTitle: ZAP Scanning Report
      template: traditional-pdf
