---
env:
  contexts:
    - name: "Testfire Context"
      urls:
        - "http://testfire.net/"
      includePaths:
        - "http://testfire.net/*"
      excludePaths:
        - "http://testfire.net/bank/main.jsp"
        - "http://testfire.net/search.jsp"
      authentication:
        method: "form"
        parameters:
          loginPageUrl: "http://testfire.net/login.jsp"
          loginRequestUrl: "http://testfire.net/doLogin"
          loginRequestBody: "uid={%username%}&passw={%password%}"
        verification:
          method: "response"
          loggedInRegex: "Sign Off"
          loggedOutRegex: "Sign In"
          pollFrequency: 60
          pollUnits: "requests"
          pollUrl: ""
          pollPostData: ""
      sessionManagement:
        method: "cookie"
        parameters: {}
      technology:
        exclude: []
      users:
        - name: "test_user"
          credentials:
            password: "demo1234"
            username: "jsmith"
  parameters:
    failOnError: false
    failOnWarning: false
    progressToStdout: true
  vars: {}
jobs:
  - parameters:
      scanOnlyInScope: true
      enableTags: false
    rules: []
    name: "passiveScan-config"
    type: "passiveScan-config"
  - parameters:
      context: "Testfire Context"
      user: "test_user"
      url: ""
      maxDuration: 1
      maxDepth: 1
      maxChildren: 0
    name: "spider"
    type: "spider"
  - parameters:
      context: "Testfire Context"
      user: "test_user"
      policy: ""
      maxRuleDurationInMins: 1
      maxScanDurationInMins: 1
    policyDefinition:
      defaultStrength: "low"
      defaultThreshold: "medium"
      rules: []
    name: "activeScan"
    type: "activeScan"
  - parameters:
      template: "traditional-pdf"
      reportDir: ""
      reportTitle: "ZAP Scanning Report"
      reportDescription: ""
    name: "report"
    type: "report"
