name: DAST Demo Env

on:
  workflow_dispatch:
jobs:
  dast:
    runs-on: ["self-hosted", "EasyBuggy"]
    name: DAST on Prem Testing Action
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Checkmarx DAST Github Action
        uses: Checkmarx/dast-github-action@v1.0.0-beta
        env:
          CX_APIKEY: ${{ secrets.AST_API_KEY }}
        with:
          command: web
          config: ${{ github.workspace }}/dast-config/zap_config.yaml
          environment_id: b776fbab-f798-4066-9f1a-38a37aca5042
          log_level: info
          base_url: https://rc.dev.cxast.net/
          verbose: true
