name: DAST Demo Env

on:
  pull_request:
    branches:
      - master
  workflow_dispatch:
jobs:
  dast:
    runs-on: ubuntu-latest
    name: Checkmarx DAST
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          path: ${{ github.event.pull_request.head.sha }}
      - name: Checkmarx DAST Github Action
        uses: Checkmarx/dast-github-action@v1.0.2
        env:
          CX_APIKEY: ${{ secrets.AST_API_KEY }}
        with:
          command: web
          # config: ${{ github.event.pull_request.head.sha }}/dast-config/zap_config_web_pass.yaml # scan that will pass (no highs)
          config: ${{ github.event.pull_request.head.sha }}/dast-config/zap_config_web_fail.yaml # scan that will fail due to highs
          environment_id: 8bb636d0-7405-4d39-96ff-b1a7fd96742b 
          fail_on: "HIGH"
          log_level: info
          base_url: https://ast.checkmarx.net/
          verbose: true
          output: ${{ github.event.pull_request.head.sha }}/output
      - name: Prepare files
        run: |
          mkdir ./tmp
          sudo cp -r ${{ github.event.pull_request.head.sha }}/output ./tmp
          sudo chown -R runner:runner ./tmp
      - uses: actions/upload-artifact@v3
        if: always()
        name: Upload Logs
        with:
          name: report
          path: ./tmp/output
