name: Altoro Mutual - Web

on:
  pull_request:
    branches:
      - master
  workflow_dispatch:
jobs:
  dast:
    runs-on: ubuntu-latest
    name: Checkmarx DAST scan
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Create output folder
        run: mkdir ${{ github.workspace }}/output_folder
      - name: Change workspace owner
        run: sudo chown -R 1000:1000 ${{ github.workspace }}
      - name: Start DAST scan
        uses: Checkmarx/dast-github-action@v1.0.4
        env:
          CX_APIKEY: ${{ secrets.AST_API_KEY }}
        with:
          command: web
          # shallow scan to pass
          #config: dast-config/Altoro_Mutual-web-pass.yaml
          # deep scan to fail
          config: dast-config/Altoro_Mutual-web-fail.yaml
          environment_id: eb6e1f65-0892-4e48-94dd-ecc02367df7e
          fail_on: HIGH
          log_level: info
          base_url: https://ast.checkmarx.net/
          verbose: true
          output: ${{ github.workspace }}/output_folder
      - name: Change output folder owner back to gh user
        run: sudo chown -R 1001:1001 ${{ github.workspace }}/output_folder
      - uses: actions/upload-artifact@v3
        name: Upload artifacts
        with:
          name: report
          path: ${{ github.workspace }}/output_folder
