name: Altoro Mutual - DAST Web
on:
  pull_request:
    branches:
      - master
  workflow_dispatch:
jobs:
  dast:
    runs-on: ubuntu-latest
    name: Checkmarx DAST - web scan
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Create output folder
        run: mkdir ${{ github.workspace }}/output_folder
      - name: Change workspace owner
        run: sudo chown -R 1000:1000 ${{ github.workspace }}
      - name: Start DAST scan
        uses: Checkmarx/dast-github-action@v1.0.6
        env:
          #CX_APIKEY: ${{ secrets.AST_API_KEY }}
          CX_APIKEY: eyJhbGciOiJIUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICIxOTY5OGFmOS1kNzI4LTQ2N2MtODU5ZS0yM2VmOGZiN2FjM2QifQ.eyJpYXQiOjE3MDczMjUwODAsImp0aSI6ImVhMDlmOTQyLTJhMzItNGI1ZS1hM2E3LTllNjQ1MDc3OWI3NCIsImlzcyI6Imh0dHBzOi8vaWFtLmNoZWNrbWFyeC5uZXQvYXV0aC9yZWFsbXMvcndfZGVtbyIsImF1ZCI6Imh0dHBzOi8vaWFtLmNoZWNrbWFyeC5uZXQvYXV0aC9yZWFsbXMvcndfZGVtbyIsInN1YiI6IjVhY2Y0MzhlLTE0ODEtNGZiMS1iZjM5LWYzZTg2OTE0ZTcyMCIsInR5cCI6Ik9mZmxpbmUiLCJhenAiOiJhc3QtYXBwIiwic2Vzc2lvbl9zdGF0ZSI6ImY2ZjYzNjkzLTQwM2UtNGVkNi04YzhmLTc3YjYxMmM4ZDMyZSIsInNjb3BlIjoiIG9mZmxpbmVfYWNjZXNzIiwic2lkIjoiZjZmNjM2OTMtNDAzZS00ZWQ2LThjOGYtNzdiNjEyYzhkMzJlIn0.BofVZL15xXtQEbNXJuz6sPK6uQZ4mOYRgE09Nt5C-Tk
        with:
          command: web
          # shallow scan to pass
          config: ${{ github.workspace }}/dast-config/Altoro_Mutual-web-pass.yaml
          # deep scan to fail 
          #config: ${{ github.workspace }}/dast-config/Altoro_Mutual-web-fail.yaml
          environment_id: 9dda76e9-d2d3-464c-a449-1855ebce337d
          fail_on: HIGH
          log_level: debug
          base_url: https://ast.checkmarx.net/
          verbose: true
          output: ${{ github.workspace }}/output_folder
      - name: Change output folder owner back to gh user
        run: sudo chown -R 1001:1001 ${{ github.workspace }}/output_folder
      - uses: actions/upload-artifact@v3
        name: Upload artifacts
        with:
          name: report
          path: ${{ github.workspace }}/output_folder

