name: Altoro Mutual - DAST API
on:
  pull_request:
    branches:
      - master
  workflow_dispatch:
jobs:
  dast:
    runs-on: ubuntu-latest
    name: Checkmarx DAST API scan
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Create output folder
        run: mkdir ${{ github.workspace }}/output_folder
      - name: Change workspace owner
        run: sudo chown -R 1000:1000 ${{ github.workspace }}
      - name: Start DAST scan
        uses: Checkmarx/dast-github-action@v1.0.5
        env:
          CX_APIKEY: ${{ secrets.AST_API_KEY }}
        with:
          command: api
          config: dast-config/Altoro_Mutual-API.yaml
          openapi: dast-config/Altoro_Mutual-OpenAPI.yaml
          environment_id: 1e915f8d-8079-4ee0-88df-2eb9b91f2d2f
          # comment out fail_on if we don't want to fail
          # fail_on: HIGH
          log_level: debug
          base_url: https://ast.checkmarx.net/
          verbose: true
          output: ${{ github.workspace }}/output_folder
      - name: Change output folder owner back to gh user
        run: sudo chown -R 1001:1001 ${{ github.workspace }}/output_folder
      - uses: actions/upload-artifact@v3
        name: Upload artifacts
        with:
          name: report
          path: ${{ github.workspace }}/output_folder
