name: DAST API Demo Env

on:
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  dast:
    runs-on: ["self-hosted", "EasyBuggy"]
    name: DAST on Prem Testing Action
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          path: dast
      - name: Checkmarx DAST Github Action
        uses: Checkmarx/dast-github-action@v1.0.2
        env:
          CX_APIKEY: ${{ secrets.AST_API_KEY }}
        with:
          command: api
          config: dast/dast-config/zap_config_api.yaml
          openapi: dast/dast-config/openapi.yaml
          project_id: a4b38f15-041d-43d1-a9d4-d12362a5f5b6
          environment_id: 444ccff9-e93f-4329-833f-7b3921a14ac6 
          log_level: info
          base_url: https://deu.ast.checkmarx.net/
          verbose: true
          output: ./output
      - uses: actions/upload-artifact@v3
        if: always()        
        name: Upload Logs        
        with:
          name: report
          path: dast/output
