name: DAST API Demo Env

on:
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  dast:
    runs-on: ["self-hosted", "EasyBuggy"]
    name: DAST on Prem Testing Action
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Checkmarx DAST Github Action
        uses: Checkmarx/dast-github-action@v1.0.1-beta
        env:
          CX_APIKEY: ${{ secrets.AST_API_KEY }}
        with:
          command: api
          config: ${{ github.workspace }}/dast-config/zap_config_api.yaml
          openapi: ${{ github.workspace }}/dast-config/openapi.yaml
          project_id: a4b38f15-041d-43d1-a9d4-d12362a5f5b6
          environment_id: a329f82e-a529-4a28-90d0-b9cd7fa11cb2
          log_level: info
          base_url: https://deu.ast.checkmarx.net/
          verbose: true

