name: Altoro Mutual - DAST Web for Lily
on:
  pull_request:
    branches:
      - master
  workflow_dispatch:
jobs:
  dast:
    runs-on: ubuntu-latest
    name: Checkmarx DAST - web scan
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2
      - name: Create output folder
        run: mkdir ${{ github.workspace }}/output_folder
      - name: Change workspace owner
        run: sudo chown -R 1000:1000 ${{ github.workspace }}
      - name: Start DAST scan
        uses: Checkmarx/dast-github-action@v2.3.0
        env:
          CX_APIKEY: ${{ secrets.LILY_AST_API_KEY }}
        with:
          command: web
          config: ${{ github.workspace }}/dast-config/Altoro_Mutual-web-lily.yaml
          environment_id: ed6f56c8-5c51-4671-b4c5-a00339608fd8d
          log_level: debug
          base_url: https://us.ast.checkmarx.net/
          verbose: true
          output: ${{ github.workspace }}/output_folder
      - name: Change output folder owner back to gh user
        run: sudo chown -R 1001:1001 ${{ github.workspace }}/output_folder
      - uses: actions/upload-artifact@v4.4.3
        name: Upload artifacts
        with:
          name: report
          path: ${{ github.workspace }}/output_folder
